# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DouYuWL0801' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DouYuWL0801

pod 'Alamofire', '~> 4.0.1'
pod 'Kingfisher', '~> 3.1.1'

end
